<?php
/**
 * Link         :   http://www.phpcorner.net
 * User         :   qingbing<780042175@qq.com>
 * Date         :   2019-02-24
 * Version      :   1.0
 */

namespace Gt\Components;


use Gt\Models\LoginForm;

class WebUser extends \Abstracts\WebUser
{
    /**
     * 获取当前登录用户的信息
     * @return array
     */
    protected function getUser()
    {
        return [
            'username' => $this->getUsername(),
        ];
    }

    /**
     * 登录成功后调用，如果使用需要子类重写
     * @param UserIdentity $identity
     * @throws \Exception
     */
    protected function afterLogin($identity)
    {
        // 销毁登录消息
        \Captcha::getCaptchaAction(LoginForm::$captchaAction)->destroyState();
        parent::afterLogin($identity); // TODO: Change the autogenerated stub
    }
}